version: '3'
services:


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - "8888:80"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=school 
    links:
      - db 

  db:
    image: mysql:latest
    command: --init-file /init.sql
    # command: --default-authentication-plugin=mysql_native_password 
    ports:
      - '3306:3306'
    environment:
      # - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=school
      # - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
      # - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql
      - ./init.sql:/init.sql

  backend-spring:
    # command: mvn clean install
    build:
      context: ./
      dockerfile: ./backend-springboot/Dockerfile
    image: backend-springboot/api

    ports:
      - "8081:8081"
      - "5006:5006"
    volumes:
      - "./backend-springboot:/home/backend-springboot"
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5007 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE=dev
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=school
#      - MYSQL_ROOT_HOST= '%'
    links:
      - db
      
 
